TekMarket/Controllers/DotNetReportController.cs
using TekMarket.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Net.Http;
using System.Threading.Tasks;
using OfficeOpenXml;
using System.Text.RegularExpressions;

namespace TekMarket.Controllers
{
    [Authorize]
    [RoutePrefix("admin/dotnetreport")]
    public class DotNetReportController : Controller
    {
        [Route()]
    

    public ActionResult Index()
        {
            return View();
        }

        [Route("Report")]
        public ActionResult Report(int reportId, string reportName, string reportDescription, bool includeSubTotal, bool showUniqueRecords,
            bool aggregateReport, bool showDataWithGraph, string reportSql, string connectKey, string reportFilter, string reportType, int selectedFolder)
        {
            var model = new DotNetReportModel
            {
                ReportId = reportId,
                ReportType = reportType,
                ReportName = HttpUtility.UrlDecode(reportName),
                ReportDescription = HttpUtility.UrlDecode(reportDescription),
                ReportSql = reportSql,
                ConnectKey = connectKey,
                IncludeSubTotals = includeSubTotal,
                ShowUniqueRecords = showUniqueRecords,
                ShowDataWithGraph = showDataWithGraph,
                SelectedFolder = selectedFolder,
                ReportFilter = reportFilter // json data to setup filter correctly again
            };

            return View(model);
        }

        [Route("GetLookupList")]
        public JsonResult GetLookupList(string lookupSql, string connectKey)
        {
            var sql = Decrypt(lookupSql);

            // Uncomment if you want to restrict max records returned
            sql = sql.Replace("SELECT ", "SELECT TOP 500 ");
            
            var json = new StringBuilder();
            var dt = new DataTable();
            using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings[connectKey].ConnectionString))
            {
                conn.Open();
                var command = new SqlCommand(sql, conn);
                var adapter = new SqlDataAdapter(command);

                adapter.Fill(dt);
            }

            int i=0;
            foreach (DataRow dr in dt.Rows)
            {
                json.AppendFormat("{{\"id\": \"{0}\", \"text\": \"{1}\"}}{2}", dr[0], dr[1], i!=dt.Rows.Count-1 ? "," : "");
                i+=1;            
            }

            return Json((new JavaScriptSerializer()).DeserializeObject("["+json.ToString()+"]"), JsonRequestBehavior.AllowGet);
        }


        [Route("RunReport")]
        public JsonResult RunReport(string reportSql, string connectKey, string reportType, int pageNumber = 1, int pageSize = 50, string sortBy = null, bool desc = false)
        {
            var sql = Decrypt(reportSql);

            try
            {
                if (!String.IsNullOrEmpty(sortBy))
                {
                    if (sortBy.StartsWith("DATENAME(MONTH, "))
                    {
                        sortBy = sortBy.Replace("DATENAME(MONTH, ", "MONTH(");
                    }
                    sql = sql.Substring(0, sql.IndexOf("ORDER BY")) + "ORDER BY " + sortBy + (desc ? " DESC" : "");
                }

                // Execute sql
                var dt = new DataTable();
                var dtPaged = new DataTable();
                using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings[connectKey].ConnectionString))
                {
                    conn.Open();
                    var command = new SqlCommand(sql, conn);
                    var adapter = new SqlDataAdapter(command);

                    adapter.Fill(dt);
                }

                dtPaged = (dt.Rows.Count > 0) ? dtPaged = dt.AsEnumerable().Skip((pageNumber - 1) * pageSize).Take(pageSize).CopyToDataTable(): dt;                

                var model = new DotNetReportResultModel
                {
                    ReportData = DataTableToDotNetReportDataModel(dtPaged, sql),
                    Warnings = GetWarnings(sql),
                    ReportSql = sql,
                    ReportDebug = Request.Url.Host.Contains("localhost"),
                    Pager = new DotNetReportPagerModel
                    {
                        CurrentPage = pageNumber, 
                        PageSize = pageSize,
                        TotalRecords = dt.Rows.Count,
                        TotalPages =(int) ((dt.Rows.Count/pageSize)+1)
                    }
                };

                return new JsonResult()
                {
                    Data = model,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    MaxJsonLength = Int32.MaxValue
                };

            }

            catch (Exception ex)
            {
                var model = new DotNetReportResultModel
                {
                    ReportData = new DotNetReportDataModel(),
                    ReportSql = sql,
                    HasError = true,
                    Exception = ex.Message
                };

                return Json(model, JsonRequestBehavior.AllowGet);
            }
        }

        [Route("Dashboard")]
		public async Task<ActionResult> Dashboard()
        {
            var model = new List<DotNetReportModel>();

            using (var client = new HttpClient())
            {

                var content = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("account", ConfigurationManager.AppSettings["dotNetReport.accountApiToken"]),
                    new KeyValuePair<string, string>("dataConnect", ConfigurationManager.AppSettings["dotNetReport.dataconnectApiToken"]),
                    new KeyValuePair<string, string>("clientId",""), // Pass your Client Id
					new KeyValuePair<string, string>("userId","") // Pass your User Id
                });

                var response = await client.PostAsync(new Uri(ConfigurationManager.AppSettings["dotNetReport.apiUrl"] + "/ReportApi/LoadDashboard"), content);
                var stringContent = await response.Content.ReadAsStringAsync();

                model = (new JavaScriptSerializer()).Deserialize<List<DotNetReportModel>>(stringContent);
            }

            return View(model);
        }

        [Route("DownloadExcel")]
        [HttpPost]
        public ActionResult DownloadExcel(string reportSql, string connectKey, string reportName)
        {
            var sql = Decrypt(reportSql);

            // Execute sql
            var dt = new DataTable();
            using (var conn = new SqlConnection(ConfigurationManager.ConnectionStrings[connectKey].ConnectionString))
            {
                conn.Open();
                var command = new SqlCommand(sql, conn);
                var adapter = new SqlDataAdapter(command);

                adapter.Fill(dt);
            }

            
            Response.ClearContent();

            using (ExcelPackage xp = new ExcelPackage())
            {

                ExcelWorksheet ws = xp.Workbook.Worksheets.Add(reportName);

                int rowstart = 1;
                int colstart = 1;
                int rowend = rowstart;
                int colend = dt.Columns.Count;

                ws.Cells[rowstart, colstart, rowend, colend].Merge = true;
                ws.Cells[rowstart, colstart, rowend, colend].Value = reportName;
                ws.Cells[rowstart, colstart, rowend, colend].Style.Font.Bold = true;
                ws.Cells[rowstart, colstart, rowend, colend].Style.Font.Size = 14;

                rowstart += 2;
                rowend = rowstart + dt.Rows.Count;
                ws.Cells[rowstart, colstart].LoadFromDataTable(dt, true);
                ws.Cells[rowstart, colstart, rowstart, colend].Style.Font.Bold = true;

                int i = 1;
                foreach (DataColumn dc in dt.Columns)
                {
                    if (dc.DataType == typeof(decimal))
                        ws.Column(i).Style.Numberformat.Format = "#0.00";

                    if (dc.DataType == typeof(DateTime))
                        ws.Column(i).Style.Numberformat.Format = "dd/mm/yyyy";

                    i++;
                }
                ws.Cells[ws.Dimension.Address].AutoFitColumns();


                Response.AddHeader("content-disposition", "attachment; filename=" + reportName + ".xlsx");
                Response.ContentType = "application/vnd.ms-excel";
                Response.BinaryWrite(xp.GetAsByteArray());
                Response.End();

            }

            
            Response.End();
            
            return View();
        }


        /// <summary>
        /// Method to Deycrypt encrypted sql statement. PLESE DO NOT CHANGE THIS METHOD
        /// </summary>
        private string Decrypt(string encryptedText)
        {

            byte[] initVectorBytes = Encoding.ASCII.GetBytes("yk0z8f39lgpu70gi"); // PLESE DO NOT CHANGE THIS KEY
            int keysize = 256;

            byte[] cipherTextBytes = Convert.FromBase64String(encryptedText.Replace("%3D","="));
            var passPhrase = ConfigurationManager.AppSettings["dotNetReport.privateApiToken"].ToLower();
            using (PasswordDeriveBytes password = new PasswordDeriveBytes(passPhrase, null))
            {
                byte[] keyBytes = password.GetBytes(keysize / 8);
                using (RijndaelManaged symmetricKey = new RijndaelManaged())
                {
                    symmetricKey.Mode = CipherMode.CBC;
                    using (ICryptoTransform decryptor = symmetricKey.CreateDecryptor(keyBytes, initVectorBytes))
                    {

TekMarket/Views/DotNetReport/Dashboard.cshtml
@using System.Configuration
@model List<DotNetReportModel>
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/shared/_Layout.Report.cshtml";
    //Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Dashboard</h2>

@section scripts{
    <script type="text/javascript">

    $(document).ready(function () {
         var reports = [];

        @foreach (var r in Model)
        {
            @:reports.push({reportSql: "@r.ReportSql", reportId: @r.ReportId, reportFilter: htmlDecode('@HttpUtility.UrlDecode(r.ReportFilter)'), connectKey: "@r.ConnectKey"});
        }

        var vm = new dashboardViewModel({
            runReportUrl: "@Url.Action("Report")",
            execReportUrl: "@Url.Action("RunReport")",
            reportWizard: $("#filter-panel"),
            lookupListUrl: "@Url.Action("GetLookupList")",
            apiUrl: "@ConfigurationManager.AppSettings["dotNetReport.apiUrl"]",
            accountApiToken: "@ConfigurationManager.AppSettings["dotNetReport.accountApiToken"]", // Your Account Api Token from your http://dotnetreport.com Account
            dataconnectApiToken: "@ConfigurationManager.AppSettings["dotNetReport.dataconnectApiToken"]", // Your Data Connect Api Token from your http://dotnetreport.com Account
            reportMode: "execute",
            reports: reports
        });

        ko.applyBindings(vm);

        $(window).resize(function(){
            vm.drawChart();
        });
      });
    </script>
}

<div data-bind="foreach: reports">
    <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading panel-nocollapse">
                <span data-bind="text: ReportName"></span>
                <div class="pull-right">
                    @using (Html.BeginForm("DownloadExcel", "Report", FormMethod.Post))
                    {
                        <input type="hidden" id="reportSql" name="reportSql" data-bind="value: currentSql" />
                        <input type="hidden" id="connectKey" name="connectKey" data-bind="value: currentConnectKey" />
                        <input type="hidden" id="reportName" name="reportName" data-bind="value: ReportName" />
                        <button type="submit" class="btn btn-default btn-xs"><span class="fa fa-file-excel-o"></span></button>
                    }
                </div>
                <a data-bind="attr: {href: '@Url.Action("Index","Report")?reportId=' + ReportID()}" class="btn btn-default btn-xs pull-right">
                    <i class="fa fa-pencil-square-o" title="Edit Report"></i>
                </a>
            </div>
            <div class="panel-body list-overflow">
                <p data-bind="html: ReportDescription">
                </p>
                <div data-bind="with: ReportResult">
                    <div data-bind="template: 'report-template', data: $data"></div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="small" data-bind="with: pager">
                    <div class="form-group pull-left total-records">
                        <span data-bind="text: 'Total Records: ' + totalRecords()"></span><br />
                    </div>
                    <div class="form-group pull-right" data-bind="if: pages()>1">
                        <div data-bind="template: 'pager-template', data: $data"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="checkout-right-basket">
    <a href="/admin/home" class="btn btn-primary">Back to Admin Panel</a>
</div>
<div class="clearfix"></div>

TekMarket/Views/DotNetReport/Report.cshtml
@using System.Configuration
@using System.Data
@model DotNetReportModel
@{
    ViewBag.Title = "Report";
    Layout = "../shared/_Layout.Report.cshtml";
}

@*
    This razor view renders the Report from the Data Table as a Html Table. You have complete control over this page and you can change the code and style to meet your requirements.

    Its Recommended you use it as is, and only change styling as needed to match your application. You will be responsible for managing and maintaining any changes.

    Note: To allow bigger file downloads in Excel, Please increase maxRequestLength in web.config. For example, <httpRuntime maxRequestLength="1048576" />

*@

@section scripts{
    <script type="text/javascript">
    function printReport() {
        var printWindow = window.open("");
        printWindow.document.open();
        printWindow.document.write('<html><head>'+
                                '<link href="/Content/bootstrap.css" rel="stylesheet" />'+
                                '</head><body>' + $('.report-inner').html() +
                                '</body></html>');

        setTimeout(function(){
            printWindow.print();
            printWindow.close();
        }, 250);
    }

    function downloadExcel() {
        $("#downloadExcel").submit();
    }

    $(document).ready(function () {
        var vm = new reportViewModel({
            runReportUrl: "@Url.Action("Report")",
            execReportUrl: "@Url.Action("RunReport")",
            reportWizard: $("#filter-panel"),
            lookupListUrl: "@Url.Action("GetLookupList")",
            apiUrl: "@ConfigurationManager.AppSettings["dotNetReport.apiUrl"]",
            accountApiToken: "@ConfigurationManager.AppSettings["dotNetReport.accountApiToken"]", // Your Account Api Token from your http://dotnetreport.com Account
            dataconnectApiToken: "@ConfigurationManager.AppSettings["dotNetReport.dataconnectApiToken"]", // Your Data Connect Api Token from your http://dotnetreport.com Account
            reportFilter: htmlDecode('@HttpUtility.UrlDecode(Model.ReportFilter)'),
            reportMode: "execute",
            reportSql: "@Model.ReportSql",
            reportConnect: "@Model.ConnectKey"
        });

        ko.applyBindings(vm);
        vm.LoadReport(@Model.ReportId, true);

        $(window).resize(function(){
            vm.DrawChart();
        });
    });

    </script>
}

<div data-bind="with: ReportResult">

    <!-- ko ifnot: HasError -->
    <div class="report-view" data-bind="with: $root">
        @using (Html.BeginForm("DownloadExcel", "DotNetReport", FormMethod.Post, new { id = "downloadExcel" }))
        {
            <input type="hidden" id="reportSql" name="reportSql" data-bind="value: currentSql" />
            <input type="hidden" id="connectKey" name="connectKey" data-bind="value: currentConnectKey" />
            <input type="hidden" id="reportName" name="reportName" data-bind="value: ReportName" />
        }

        <div class="pull-right">
            <a href="@Url.Action("Index","DotNetReport")?folderId=@Model.SelectedFolder" class="btn btn-primary">
                Back to Reports
            </a>
            <a href="@Url.Action("Index","DotNetReport")?reportId=@Model.ReportId&folderId =@Model.SelectedFolder" class="btn btn-primary">
                Edit Report
            </a>
            <button type="button" class="btn btn-default" onclick="printReport();">
                <span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print Report
            </button>
            <button class="btn btn-default" onclick="downloadExcel();" data-bind="visible: !isChart() || ShowDataWithGraph()">
                <span class="fa fa-file-excel-o"></span> Export to Excel
            </button>

            @*<div class="dropdown pull-right">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <span class="fa fa-download"></span> Export
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#" onclick="downloadExcel();" data-bind="visible: !isChart() || ShowDataWithGraph()">
                                <span class="fa fa-file-excel-o"></span> Excel
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa fa-file-pdf-o"></span> PDF
                            </a>
                        </li>

                    </ul>
                </div>*@

        </div>
        <br />
        <br />
        <div style="clear: both;"></div>
        <br />
        <div class="panel panel-default" data-bind="visible: FlyFilters().length>0">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a data-toggle="collapse" data-target="#filter-panel" href="#">
                        <i class="fa fa-filter"></i> Choose filter options
                    </a>
                </h3>
            </div>
            <div id="filter-panel" class="panel-collapse">
                <div class="panel-body">
                    <!-- ko foreach: FlyFilters -->
                    <div class="row">

                        <div class="col-sm-5 col-xs-4">
                            <div data-bind="with: Field" class="checkbox">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" title="Apply this filter" data-bind="checked: $parent.Apply" /><span data-bind="text: selectedFieldName"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div data-bind="with: Field" class="col-sm-2 col-xs-3">
                            <div class="form-group" data-bind="if: $parent.Apply">
                                <select class="form-control" data-bind="options: fieldFilter, value: $parent.Operator" required></select>
                            </div>
                        </div>
                        <div data-bind="with: Field" class="col-xs-5">
                            <div data-bind="if: $parent.Apply">
                                @Html.Partial("_reportFilter")
                            </div>
                        </div>
                    </div>
                    <!-- /ko -->
                    <button class="btn btn-primary" data-bind="click: RunReport">Refresh Report</button>
                </div>
            </div>
        </div>
        <div data-bind="if: canDrilldown">
            <button class="btn btn-default btn-xs" data-bind="click: ExpandAll">Expand All</button>
            <button class="btn btn-default btn-xs" data-bind="click: CollapseAll">Collapse All</button>
            <br />
            <br />
        </div>
        <div class="report-menubar">
            <div class="col-xs-12 col-centered" data-bind="with: pager">
                <div class="form-inline" data-bind="visible: pages()">
                    <div class="form-group pull-left total-records">
                        <span data-bind="text: 'Total Records: ' + totalRecords()"></span><br />
                    </div>
                    <div class="pull-left">
                        <button class="btn btn-default btn-sm" onclick="downloadExcel();" data-bind="visible: !$root.isChart() || $root.ShowDataWithGraph()" title="Export to Excel">
                            <span class="fa fa-file-excel-o"></span>
                        </button>
                    </div>
                    <div class="form-group pull-right">
                        <div data-bind="template: 'pager-template', data: $data"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="report-canvas">
            <div class="report-container">
                <div class="report-inner">
                    <h2 data-bind="text: ReportName"></h2>
                    <p data-bind="html: ReportDescription">
                    </p>
                    <div data-bind="with: ReportResult">
                        <div data-bind="template: 'report-template', data: $data"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <span>Report ran on: @DateTime.Now.ToShortDateString() @DateTime.Now.ToShortTimeString()</span>
    </div>
    <!-- /ko -->
    <!-- ko if: HasError -->
    <h2>@Model.ReportName</h2>
    <p>
        @Model.ReportDescription
    </p>

    <a href="@Url.Action("Index","DotNetReport")?folderId=@Model.SelectedFolder" class="btn btn-primary">
        Back to Reports
    </a>
    <a href="@Url.Action("Index","DotNetReport")?reportId=@Model.ReportId&folderId =@Model.SelectedFolder" class="btn btn-primary">
        Edit Report
    </a>
    <h3>An unexpected error occured while running the Report</h3>
    <hr />
    <b>Error Details</b>
    <p>
        <div data-bind="text: Exception"></div>
    </p>

    <!-- /ko -->
    <!-- ko if: ReportDebug() || HasError() -->
    <br />
    <br />
    <hr />
    <code data-bind="text: ReportSql">

    </code>
    <!-- /ko -->
</div>

TekMarket/Views/DotNetReport/_reportFilter.cshtml
<div class="form-group">
    <!-- ko if: !hasForeignKey-->
    <!-- ko if: fieldType=='DateTime'-->
    <!-- ko if: ['=','>','<','>=','<='].indexOf($parent.Operator()) != -1 -->
    <input class="form-control" data-bind="datepicker: $parent.Value" required />
    <!-- /ko -->
    <!-- ko if: ['between'].indexOf($parent.Operator()) != -1 -->
    From <input required class="form-control" data-bind="datepicker: $parent.Value" /> to <input data-bind="datepicker: $parent.Value2" class="form-control" required />
    <!-- /ko -->
    <!-- ko if: ['range'].indexOf($parent.Operator()) != -1 -->
    <select data-bind="value: $parent.Value" class="form-control">
        <option>Today</option>
        <option>This Week</option>
        <option>Last Week</option>
        <option>This Month</option>
        <option>Last Month</option>
        <option>This Year</option>
        <option>Last Year</option>
        <option>Last 30 Days</option>
    </select>
    <!-- /ko -->
    <!-- /ko -->
    <!-- ko if: ['Int','Money','Float'].indexOf(fieldType) != -1 -->
    <!-- ko if: ['=','>','<','>=','<='].indexOf($parent.Operator()) != -1 -->
    <input class="form-control" type="number" data-bind="value: $parent.Value" required />
    <!-- /ko -->
    <!-- ko if: ['between'].indexOf($parent.Operator()) != -1 -->
    From <input class="form-control" type="number" data-bind="value: $parent.Value" required /> to <input class="form-control" type="number" data-bind="value: $parent.Value2" required />
    <!-- /ko -->
    <!-- /ko -->
    <!-- ko if: fieldType=='Boolean' -->
    <select required class="form-control" data-bind="value: $parent.Value" >
        <option value="1">Yes</option>
        <option value="0">No</option>
    </select>
    <!-- /ko -->
    <!-- ko if: ['Int','Money','Float','Date','DateTime','Boolean'].indexOf(fieldType) == -1 -->
    <input class="form-control" type="text" data-bind="value: $parent.Value" required />
    <!-- /ko -->
    <!-- /ko -->
    <!-- ko if: hasForeignKey-->
    @*Show lookup list*@
    <!-- ko if: $parent.Operator()=='='-->
    <select required class="form-control" data-bind="options: $parent.LookupList, optionsText:'text', optionsValue:'id', value: $parent.Value, optionsCaption: 'Please Choose'"></select>
    <!-- /ko -->
    <!-- ko if: $parent.Operator()=='in'-->
    <select multiple class="form-control" data-bind=" select2: { placeholder: 'Please Choose', allowClear: true }, options: $parent.LookupList, optionsText:'text', optionsValue:'id', selectedOptions: $parent.Value"></select>
    <!-- /ko -->
    <!-- /ko -->
</div>