TekMarket/Models/Article.cs
namespace TekMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Article")]
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            Avis = new HashSet<Avi>();
            Qtecommandes = new HashSet<Qtecommande>();
            Qtepaniers = new HashSet<Qtepanier>();
        }

        [Key]
        [StringLength(50)]
        [Required]
        public string refarticle { get; set; }

        [Required]
        public string libelle { get; set; }

        [Column(TypeName = "text")]
        [Required]
        public string description { get; set; }


        [Required]
  
        public float? prix { get; set; }

        [Column(TypeName = "text")]
        public string image { get; set; }

        [Required]
        public long? qtedisponible { get; set; }


        [Column(TypeName = "text")]
        public string couleurdispo { get; set; }

        [StringLength(50)]
        public string idcategorie { get; set; }

        public virtual Categorie Categorie { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avi> Avis { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qtecommande> Qtecommandes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qtepanier> Qtepaniers { get; set; }
    }
}

TekMarket/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TekMarket.Models;
using System.IO;




namespace TekMarket.Controllers
{
    [Authorize]
     [RoutePrefix("Admin/Articles")]
    public class ArticlesController : Controller
    {
        private DBModel db = new DBModel();

        // GET: Articles
        [HttpGet]
        [Route]
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var articles = db.Articles.Include(a => a.Categorie);
            return View(await articles.ToListAsync());
        }

        // GET: Articles/Details/5
        [HttpGet]
        [Route("details/{id}")]
        [Authorize]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = await db.Articles.FindAsync(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Articles/Create

       //[Authorize]
        [HttpGet]
        [Route("Create")]
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.idcategorie = new SelectList(db.Categories, "id", "libelle");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Create")]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "refarticle,libelle,description,prix,qtedisponible,couleurdispo,idcategorie")] Article article)
        {
            if (ModelState.IsValid)
            {
               
                

         


                db.Articles.Add(article);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idcategorie = new SelectList(db.Categories, "id", "libelle", article.idcategorie);
            return View(article);
        }

        // GET: Articles/Edit/5
        
        [Route("Edit/{id}")]
        [Authorize]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = await db.Articles.FindAsync(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcategorie = new SelectList(db.Categories, "id", "libelle", article.idcategorie);
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Edit/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit([Bind(Include = "refarticle,libelle,description,prix,image,qtedisponible,couleurdispo,idcategorie")] Article article)
        {
            if (ModelState.IsValid)
            {
              

                db.Entry(article).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idcategorie = new SelectList(db.Categories, "id", "libelle", article.idcategorie);
            return View(article);
        }

        // GET: Articles/Delete/5
        [HttpGet]
        [Route("Delete/{id}")]
        [Authorize]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = await db.Articles.FindAsync(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("Delete/{id}")]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Article article = await db.Articles.FindAsync(id);
            db.Articles.Remove(article);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [HttpGet]
        [Route("uploadimage")]
        [Authorize]
        public ActionResult uploadImage()
        {
            return View("UploadImage");

        }



        [HttpPost]
        [Route("UploadFiles")]
        [Authorize]
        public ActionResult UploadFiles(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //setImage Path In Model Article 



                    //Method 2 Get file details from HttpPostedFileBase class    

                    if (file != null)
                    {

                        DBModel db=new DBModel();
                        List<Article> laArticles = db.Articles.ToList();

                        int i = 0;
                        while (i < laArticles.Count && laArticles.ElementAt(i).refarticle.CompareTo(file.FileName) != 0)
                        {
                            i++;

                        }

                     




                        string path = Path.Combine(Server.MapPath("~/UploadedImage"), Path.GetFileName(file.FileName));
                        file.SaveAs(path);


                        if (i < laArticles.Count)
                        {
                            laArticles.ElementAt(i).image = path;

                            db.SaveChanges();


                        }

                        String ftpUrl = "ftp://ftpupload.net/htdocs/images/";
                        String ftpUser = "epiz_22842660";
                        String ftpPass = "LIcxYNffKR7U9";

                        string filename = Path.GetFileName(file.FileName);

                        string fullPath = ftpUrl + filename;



                        FtpWebRequest ftp = (FtpWebRequest)FtpWebRequest.Create(fullPath);
                        ftp.Credentials = new NetworkCredential(ftpUser, ftpPass);

                        ftp.KeepAlive = true;
                        ftp.UseBinary = true;
                        ftp.Method = WebRequestMethods.Ftp.UploadFile;




                        FileStream fs = System.IO.File.OpenRead(Path.GetFullPath(path));


                        byte[] buffer = new byte[fs.Length];
                        fs.Read(buffer, 0, buffer.Length);
                        fs.Close();

                        Stream ftpstream = ftp.GetRequestStream();
                        ftpstream.Write(buffer, 0, buffer.Length);
                        ftpstream.Close();
                        Console.WriteLine("Done !");


                        ViewBag.FileStatus = "File uploaded successfully.";
                    }

                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading." + e.Message;
                }
            }

            return View("UploadImage");
        }


    }
}

TekMarket/Views/Articles/Create.cshtml
@model TekMarket.Models.Article

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create Product</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Article Reference", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.refarticle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.refarticle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Label", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        
  


        <div class="form-group">
            @Html.Label("Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qtedisponible, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qtedisponible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Colors", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.couleurdispo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.couleurdispo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Category ID", "idcategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idcategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idcategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="formsubmit" value="Create" class="btn btn-default" />
            </div>
        </div>
    
    

    </div>
   
            }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TekMarket/Views/Articles/Delete.cshtml
@model TekMarket.Models.Article

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Product ?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Category", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.libelle)
        </dd>

        <dt>
            @Html.Label("Label", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

        <dt>
            @Html.Label("Description", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.Label("Price", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            @Html.Label("Image", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.Label("Quantity", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qtedisponible)
        </dd>

        <dt>
            @Html.Label("Colors", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.couleurdispo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TekMarket/Views/Articles/Details.cshtml
@model TekMarket.Models.Article

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Product Details</h2>

<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Category", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.libelle)
        </dd>

        <dt>
            @Html.Label("Label", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

        <dt>
            @Html.Label("Description", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.Label("Price", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

      

        <dt>
            @Html.Label("Quantity", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qtedisponible)
        </dd>

        <dt>
            @Html.Label("Colors", htmlAttributes: new { @class = "control-label" })
        </dt>

        <dd>
            @Html.DisplayFor(model => model.couleurdispo)
        </dd>

    </dl>
</div>
<p>

    <div>
        @Html.ActionLink("Upload Product Image", "uploadImage")
    </div>
    <br/>


    @Html.ActionLink("Edit", "Edit", new { id = Model.refarticle }) |

    @Html.ActionLink("Back to List", "Index")
</p>

TekMarket/Views/Articles/Edit.cshtml
@model TekMarket.Models.Article

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit Product</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.refarticle)

        <div class="form-group">
            @Html.Label("Label", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Price", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>




        

        <div class="form-group">
            @Html.Label("Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qtedisponible, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qtedisponible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Colors", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.couleurdispo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.couleurdispo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Category ID", "idcategorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idcategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idcategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Upload Product Image", "uploadImage")
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>

TekMarket/Views/Articles/Index.cshtml
@model IEnumerable<TekMarket.Models.Article>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Products List</h2>


<table class="table">
    <h4>
        Products List
    </h4>
    <tr>
      
        <th>
            @Html.Label("Label", htmlAttributes: new {@class = "control-label col-md-2"})
        </th>
        <th>
            @Html.Label("Description", htmlAttributes: new {@class = "control-label col-md-2"})
        </th>
        <th>
            @Html.Label("Price", htmlAttributes: new {@class = "control-label col-md-2"})
        </th>
      
        <th>
            @Html.Label("Quantity", htmlAttributes: new {@class = "control-label col-md-2"})
        </th>
        <th>
            @Html.Label("Colors", htmlAttributes: new {@class = "control-label col-md-2"})
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prix)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.qtedisponible)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.couleurdispo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.refarticle}) |
                @Html.ActionLink("Details", "Details", new {id = item.refarticle}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.refarticle})
            </td>
        </tr>
    }

</table>

TekMarket/Views/Articles/UploadImage.cshtml
@model TekMarket.Models.FileUploadModel

@{
    ViewBag.Title = "UploadImage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>UploadImage</h2>
@using (Html.BeginForm("UploadFiles", "Articles", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to Product", "Index")
</div>